package common;

public enum GelaxkaMota {
	JOKALARIAGORA,
	JOKALARIABEHERA,
	JOKALARIAEZKER,
	JOKALARIAESKUIN,
	JOKALARIBONBAREKIN,
	JOKALARIASUAREKIN,
	JOKALARIAHARRAPATUTA,
	BONBA,
	SUA,
	SUBERDEA,
	SUMOREA,
	GILTZA,
	BIGUNA,
	GOGORRA,
	IRTEERA,
	BONBAESTANDA,
	ETSAIAESKUMA,
	ETSAIAEZKERRA,
	ETSAIAIESKUMA,
	ETSAIAIEZKERRA,
	IRABAZI,
	JOKALARIAULTRABONBAREKIN,
	ULTRABONBA,
	JOKALARIABURBUILA,
	BURBUILASUA;
}
